### ISSUE TITLE
Vulnerabilities

### ISSUE THREAD

**Issue by sbouix** [AMP-SCZ/subject-id-gen#6]
Can someone have a look at the detected vulnerability by dependabot?
@tashrifbillah

**Comment by tashrifbillah** [comment]
Remedies:

Upgrade next
https://github.com/AMP-SCZ/subject-id-gen/security/dependabot/yarn.lock/next/open

Upgrade path-parse
https://github.com/AMP-SCZ/subject-id-gen/security/dependabot/yarn.lock/path-parse/open
